# Generated by Django 4.0.3 on 2022-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
